export * from './address.interface';
export * from './comment.interface';
export * from './company.interface';
export * from './data.interface';
export * from './common-fields.interface';
export * from './geo.interface';
export * from './post.interface';
export * from './state.interface';
export * from './user.intreface';
